### ISSUE TITLE
arrows: data formatting

### ISSUE THREAD

**Issue by mpmatthe** [EvoMapViz/EvoMapJS#20]
Right now, the data format of "arrows.json" expects the following inputs:
- x coordinate
- y coordinate
- time 
- name

Right now, I need to calculate the x and y coordinates upfront, which can be a little tricky, because it requires some input from the visualization (see below). Thus, I would like to move the calculation of the x and y coordinates to this App.

Basically, I use the following input for calculating of the x and y coordinates:
- x and y slope parameters 
- the standardized length of the arrow

The standardized length of each arrow would be in [0,1], such that the final length of the arrow would be arrow.length * SCALE. This SCALE would typically be equal to the maximum distance any object has from the origin (let's call it max_dist). Therefore, if an arrow has length = 1 it would point across the whole map (up until its borders), whereas a shorter arrow (say, .5) would only reach across "one half" from the origin to the borders of the map. So ultimately, you would need to draw an arrow through (x,y) and rescale it such that it has length arrow.length * max_dist. To do so, it should suffice to divide the vector (x,y) by its norm and multiply the result by (arrow.length * SCALE). 

Right now, I make these computations on the input side and then provide final x, y coordinates to you. However, it would be much cleaner for me to only them in the format described above. 

Please let me know if that makes sense to you. I can also provide further details or some exemplary files / calculation, if that makes things clearer.

**Comment by vanderlindenma** [comment]
Definitely doable

**To clarify something first about arrows requiring "some input from the visualization".**

I should have been more explicit in the doc, but the arrow coordinates are currently on the same scale as the circle coordinates. For example, if 

`{"x":2.6571,"y":-0.0351,"time":"2019-06","name":"google.com","continuous_feature_1":693.1472,"discrete_feature_1":"1","discrete_feature_2":"0","discrete_feature_3":"0","discrete_feature_4":"0","discrete_feature_5":"0","discrete_feature_6":"1","discrete_feature_7":"0","discrete_feature_8":"0"}`

and 

```
{
    "name": "FACTOR 1",
    "x":2.6571,
    "y":-0.0351,
    "time":"2019-06"
  },
```

then the head of the arrow "FACTOR 1" will be right where the "google.com" circle is at time  "2019-06".

So the arrow position is related to the position of the circles as provided in inputs (these positions are on the same scale). 

But you don't have to anticipate how these are going to be cast into the D3 SVG generated by the App (which has it's own coordinate system to which transforms are applied when zooming and panning).

**To clarify how you'd like this to be implemented**

If I understand correctly, an arrow with input `length = 1` should appear in the visualization to have a length corresponding to the largest distance from any circle to the (0,0) origin across the entire dataset.

Something like :

$$ viz.length(input.length) = input.length * \left[max \sqrt{x^2 + y^2} \right],$$

where $x$ and $y$ are circle coordinates in inputs.

- [ ] One question: Should it be the max over *all* time periods, or should it be a period-specific max? 

That is, should visualisation length be a time dependent function of $input.length$:

$$ viz.length_t(input.length) = input.length * \left[max_{i \in N} \sqrt{x_{i,t}^2 + y_{i,t}^2} \right]$$

where $N$ is the set of circle indices, or a constant function of $input.length$ like

$$ viz.length(input.length) = input.length * \left[max_{i \in N, t \in T} \sqrt{x_{i,t}^2 + y_{i,t}^2} \right],$$

where $T$ is the set of time indices?

Let me know what you'd prefer. Regardless, it will slow down booting time a little but not much, and I am happy to build it in if it makes your life easier.

**Comment by mpmatthe** [comment]
Hi Martin, 

_If I understand correctly, an arrow with input length = 1 should appear in the visualization to have a length corresponding to the largest distance from any circle to the (0,0) origin across the entire dataset._

Exactly. 

_Should it be the max over all time periods, or should it be a period-specific max?_


If the arrow length stays = 1, the arrow should not change its size in the visualization. This way, the user can (correctly) infer, that the underlying factor did not lose / gain any explanatory power. So, please use the max across all time periods!

**Comment by vanderlindenma** [comment]
Thanks for the clarification. Will work on it.
